0xB10C/miningpool-observer

- .github/workflows/rust.yml
The CI was only configured for the `main` branch (while this repo has only a `master` branch) and manual execution was not enabled.
> fix: GitHub Actions Rust CI

- web/src/handler.rs
- www/robots.txt
The old robots_txt() handler function did not take custom www-dirs
into account. As the robots.txt file is not expected to change, it
can be served via static string.
closes #3
> fix: requests to /robots.txt return 404

- www/templates/subpage/template_and_block.html
Previously, the block transaction count was used for the to show the position in the template.
closes #10
> fix: missing transaction template num tx

- www/templates/templates_and_blocks.html
Pool Names with spaces where not URL encoded which made e.g.
sharing a filtered template and block page hard.
> fix: pool names not URL encoded when filtering

- Cargo.lock
- daemon/src/processing.rs
- shared/src/tags.rs
Shows a "Taproot" tag on e.g. https://miningpool.observer/missing/b8b4144d80ee5c6c10c450d4057c62745eeb37b3306e6bfbf480d4992689dc54 (a P2TR spend that currently aren't being included by F2Pool and AntPool).
> add: 'Taproot'-tag to P2TR spending transactions

- www/templates/chart/feerates.html
The feerate graph would previously not render for blocks with zero-fee
transactions. Zero values don't work with the y-axis log scale.
closes https://github.com/0xB10C/miningpool-observer/issues/27
> fix: zero-fee block feerate graph not rendering

- web/src/handler.rs
- web/src/main.rs
- www/templates/rss/missing.xml
Can be found under /missing/feed.xml and contains txid, tags and a link to the /missing/<txid> page for this transaction.
closes #31
> add: RSS feed for missing transactions

- daemon-config.toml.example
- daemon/src/db.rs
- daemon/src/main.rs
- daemon/src/processing.rs
- shared/src/config.rs
When adding new tags, the tags for the transactions in the database can now be updated. This can be controlled via the configuration parameter `retag_transactions` (true/false).
Closes https://github.com/0xB10C/miningpool-observer/issues/31
> add: functionallity to re-tag transactions

- README.md
- docs/self-hosting.md
This avoids the need to apply a patch and self compile.
https://github.com/bitcoin/bitcoin/pull/18772 was merged and made it into ~v23.0~ v22.0
(haven't tested this yet)
> Bump minimum Bitcoin Core to v22

- .github/workflows/rust.yml
- daemon/Cargo.toml
- daemon/src/main.rs
- daemon/src/processing.rs
- shared/src/model.rs
- web/Cargo.toml
- web/src/db.rs
- web/src/main.rs
Next to cleaning up a bit, we now fail the CI if there are warnings.
Closes https://github.com/0xB10C/miningpool-observer/issues/39
> cleanup: resolve build warnings

- contrib/miningpool-observer-daemon.service
- contrib/miningpool-observer-web.service
- docs/self-hosting.md
Builds on top of #38.
This adds some additional instructions for folks unfamiliar with Rust, as well as two basic systemd unit files.
> Improve self-hosting instructions

- web-config.toml.example
This allows using a relative path for the "www" directory. 
Discussed in https://github.com/0xB10C/miningpool-observer/pull/40#discussion_r971808209
> change: drop "./" from www_dir_path in example

- contrib/miningpool-observer-daemon.service
This prevents "ThreadRPCServer incorrect password attempt from 127.0.0.1:..." errors.
I'm using cookie based authentication, and the cookie changes every time bitcoind is restarted.
There might be a more elegant way to fix this, but this works. I haven't had this problem with c-lightning, electrs and nbexplorer, so their implementation might provide some hints.
> systemd: restart when bitcoind restarts

- diesel.toml
- shared/src/schema.patch
- shared/src/schema.rs
During the upgrade to diesel 2.0 in the previous commits, the schema.rs file wasn't regenerated. Diesel 2.0 now supports PostgreSQL arrays containing NULL values. See https://diesel.rs/guides/migration_guide.html#changed-nullability-of-array-elements
We don't use NULL values in arrays and remove the Nullable wrapper in a patch as described in the 1.4 to 2.0 migration guide. The patch might need to be updated if more tables using PostgreSQL arrays are added.
> fix: regenerate schema.rs after upgrading to diesel 2.0

- daemon/src/main.rs
- daemon/src/metrics.rs
- daemon/src/processing.rs
- migrations/2023-04-08-105025_add_template_sigops_to_block_table/down.sql
- migrations/2023-04-08-105025_add_template_sigops_to_block_table/up.sql
- shared/src/model.rs
- shared/src/schema.patch
- shared/src/schema.rs
- www/templates/macro/template_and_block.html
This adds the sigops of queried block templates to the to the template information log outputs, saves them in the database which allows showing them on the "template & block" page, and adds a Prometheus metric for the template sigops.
Recently, two blocks were mined by F2Pool which were invalid due to having a few extra sigops (80_000 is the maximum per consensus rules). This provides more information about how many sigops were in a Bitcoin Core block template at that point.
We don't have sigops counts for old templates. Sigops will only be displayed for new templates. 
closes #61
> log, show, and provide a metric for template sigops

- Cargo.lock
- daemon/Cargo.toml
The rawtx-rs crate was build from master before. As the master branch of rawtx-rs is now on rust-bitcoin 0.30, building miningpool-observer fails.
> fix: pin rawtx-rs to v0.1.1

- Cargo.lock
The other mpo-0.17 commit tried to parse decimal fees from `getblock verbositiy=2` as sats.
```
INFO [stats] New Template based on 000000000000000000039053aa5c5efe2b9b8cb9222603cc17261f0e80138836 | height 784827 | 3260 tx | coinbase 6.42483494 BTC | sigops 14976
ERROR [rpc] Could not get the txids and fees for block with the hash 000000000000000000039053aa5c5efe2b9b8cb9222603cc17261f0e80138836 from the Bitcoin Core RPC server: JSON-RPC error: JSON decode error: invalid type: floating point `0.00150794`, expected u64 at line 1 column 4043
```
> fix: use correct commit of mpo-0.17 branch

- Cargo.lock
- daemon/Cargo.toml
- daemon/src/processing.rs
- migrations/2023-04-10-204659_add_remaining_sigops_fields/down.sql
- migrations/2023-04-10-204659_add_remaining_sigops_fields/up.sql
- shared/src/model.rs
- shared/src/schema.patch
- shared/src/schema.rs
- shared/src/tags.rs
- web/src/util.rs
- www/templates/macro/missing.html
- www/templates/macro/template_and_block.html
- www/templates/macro/transaction.html
Currently, only sigops for templates are stored and shown.
> Store and show sigops for transactions blocks

- web/src/db.rs
This optimizes the SQL queries a bit. However, it also reduces the (very old) data we'd potentially show to the user.
Another option could be [Materialized Views](https://www.postgresql.org/docs/current/rules-materializedviews.html) that are refreshed on every block (i.e. every time we insert new data). This would take more effort to implement. Maybe something for the future.
fixes https://github.com/0xB10C/miningpool-observer/issues/69
> Performance improvements for /missing

- www/templates/macro/template_and_block.html
For sanctioned transactions on the template and block page, the YOUNG tag was added multiple times.
> fix: the 'young' tag was added multiple times

- daemon/src/model.rs
- daemon/src/processing.rs
- www/templates/subpage/template_and_block.html
The previous implementation build packages with a global view of the available transactions. This is different from how Bitcoin Core inserts packages into a block template. For smoother feerate distribution plots, the package building algorithm changed to only account for local packages (i.e. transactions next to each other in the block). This also simplifies the package building function as a whole.
before: 
after:
> fix: build tx packages similar to Bitcoin Core

- Cargo.lock
- daemon/src/processing.rs
- web/src/main.rs
- web/src/model.rs
retrying #82 
```
Updating crates.io index
Updating git repository `https://github.com/0xb10c/rust-bitcoincore-rpc`
Updating actix-codec v0.5.0 -> v0.5.2
Updating actix-files v0.6.2 -> v0.6.6
Updating actix-http v3.3.1 -> v3.9.0
Updating actix-macros v0.2.3 -> v0.2.4
Updating actix-router v0.5.1 -> v0.5.3
Updating actix-rt v2.8.0 -> v2.10.0
Updating actix-server v2.2.0 -> v2.5.0
Updating actix-web v4.3.1 -> v4.9.0
Updating actix-web-codegen v4.2.0 -> v4.3.0
Adding addr2line v0.24.1
Removing adler v1.0.2
Adding adler2 v2.0.0
Removing ahash v0.7.6
Removing ahash v0.8.3
Adding ahash v0.8.11
Updating aho-corasick v0.7.20 -> v1.1.3
Adding android-tzdata v0.1.1
Updating arrayref v0.3.7 -> v0.3.9
Updating arrayvec v0.7.2 -> v0.7.6
Removing askama_escape v0.10.3
Updating autocfg v1.1.0 -> v1.3.0 …
```
> update: deps to fix compilation with rust 1.80 (2nd attempt)

- Cargo.lock
- daemon/Cargo.toml
- daemon/src/processing.rs
- shared/Cargo.toml
Next to general house keeping, this also enables compatibility with Bitcoin Core v28.
> update rawtx-rs and bitcoin-pool-identification dependecies

- web/src/handler.rs
- web/src/main.rs
- web/src/ogimage.rs
- www/templates/index.html
- www/templates/macro/template_and_block.html
- www/templates/missing-sanctioned.html
- www/templates/nav.html
Shows sanctioned transactions missing from blocks. Similar to the RSS feed, but a bit more user friendly.
closes https://github.com/0xB10C/miningpool-observer/issues/87
> add: /missing-sanctioned page

- daemon/src/db.rs
- daemon/src/processing.rs
- migrations/2025-01-17-100000_make_block_id_a_random_bigserial/down.sql
- migrations/2025-01-17-100000_make_block_id_a_random_bigserial/up.sql
- shared/src/model.rs
- shared/src/schema.patch
- shared/src/schema.rs
- web/src/db.rs
This allows to better import old backups. Previously, the block id's would always start at 1 and would thus overlap.
closes #91
> change: use random bigint as block id
